"" basic settings
set nocompatible			" set not compatible with vi
set showmatch               " show matching 
set ignorecase              " case insensitive 
set mouse=v                 " middle-click paste with 
set hlsearch                " highlight search 
set incsearch               " incremental search
set tabstop=4               " number of columns occupied by a tab 
set softtabstop=4           " see multiple spaces as tabstops so <BS> does the right thing
" set expandtab               " converts tabs to white space
set shiftwidth=4            " width for autoindents
set autoindent              " indent a new line the same amount as the line just typed
set number                  " add line numbers
set relativenumber
set wildmode=longest,list   " get bash-like tab completions
" set cc=80                  " set an 80 column border for good coding style
filetype plugin indent on   "allow auto-indenting depending on file type
syntax on                   " syntax highlighting
set mouse=a                 " enable mouse click
set clipboard=unnamedplus   " using system clipboard
filetype plugin on
" set cursorline              " highlight current cursorline
set ttyfast                 " Speed up scrolling in Vim
" set spell                 " enable spell check (may need to download language package)
 set noswapfile            " disable creating swap file
"  set backupdir=~/.cache/vim " Directory to store backup files
set laststatus=2			" set up status line

" netrw
" let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 0
let g:netrw_altv = 1
" let g:netrw_winsize = 25
" augroup ProjectDrawer
"   autocmd!
"   autocmd VimEnter * :Vexplore
" augroup END

"" plugins

" gruvbox8
colorscheme gruvbox8

" fzf
set rtp+=/usr/local/opt/fzf	" installed with homebrew
set rtp+=~/.fzf				" installed with git
" ctrl-p for fuzzy file search
nnoremap <c-p> :FZF <enter>

" lightline
let g:lightline = {
	\ 'colorscheme': 'gruvbox8',
	\ }
