"" basic settings
set nocompatible			" set not compatible with vi
" set showmatch               " show matching 
set ignorecase              " case insensitive 
set mouse=v                 " middle-click paste with 
set hlsearch                " highlight search 
set incsearch               " incremental search
set tabstop=4               " number of columns occupied by a tab 
set softtabstop=4           " see multiple spaces as tabstops so <BS> does the right thing
" set expandtab               " converts tabs to white space
set shiftwidth=4            " width for autoindents
set autoindent              " indent a new line the same amount as the line just typed
set number                  " add line numbers
set relativenumber
set wildmenu				" navigate tab completion
set wildmode=longest,full   " tab completion
" set cc=80                  " set an 80 column border for good coding style
filetype plugin indent on   "allow auto-indenting depending on file type
syntax on                   " syntax highlighting
set mouse=a                 " enable mouse click
" set clipboard=unnamedplus   " using system clipboard
filetype plugin on
" set cursorline              " highlight current cursorline
set ttyfast                 " Speed up scrolling in Vim
" set spell                 " enable spell check (may need to download language package)
 set noswapfile            " disable creating swap file
"  set backupdir=~/.cache/vim " Directory to store backup files
set laststatus=2			" set up status line
set background=dark			" dark mode

" terminal
set termwinscroll=1000
nnoremap <c-@> :terminal ++curwin<cr>

" netrw
nnoremap <c-n> :Explore<cr>

"" gui
set guifont=Iosevka\ Fixed\ Slab:h14

"" plugins

" gruvbox8
colorscheme gruvbox8

" lightline
let g:lightline = {
	\ 'colorscheme': 'gruvbox8',
	\ }

" ale

let g:ale_completion_enabled = 1
set omnifunc=ale#completion#OmniFunc

"" language-specific settings

" scheme and friends
autocmd Filetype scheme let b:AutoPairs={'(':')', '[':']', '{':'}','"':'"','```':'```','"""':'"""',"'''":"'''"}
autocmd Filetype scheme set expandtab
